### ISSUE TITLE
Wrong hovertext with 7-day average

### ISSUE THREAD

**Issue by bildanderwand** [covid-19-Re/shiny-dailyRe#7] opened 2020-08-12 09:35 UTC
Hey, I just mentioned that the case numbers in the hovertext is wrong if you select the 7-day average.

Example:
Look at Switzerland
Set "Display case data as ..." to "7-day average".
2020-03-29 shows 433, but the bar is higher than 900.

See also the screenshot.

By the way: I really like your shiny app, one of few really useful online COVID-19 interfaces. Thanks for your work!

![wrong_numbers](https://user-images.githubusercontent.com/68001466/89999632-5738dd80-dc8f-11ea-96f8-872e34eac6e8.png)

**Comment by dcangst** [comment] 2020-08-12 11:24
Thanks for your message! The wrong labels you saw were caused by a bug, it is now fixed in commit 2a61a2b88ddbf4092b8499376098ced5f75b78db.
thank you very much for letting us know!

**Closed as completed by dcangst** 2020-08-12 11:24 UTC
